
baseurl = "/"
title = "My blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "La tia Romy Restaurante"
    description = "Mi blog y publicaciones"
    github = "https://www.instagram.com/restauranttiaromy/?hl=es"
    twitter = "https://twitter.com/mrivaslezama"
    email = "romyrestau@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"